name: Build LaTeX PDF

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: danteev/latex:latest  # Use TeX Live with xelatex already installed

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Compile with xelatex
        run: |
          mkdir -p build
          xelatex -output-directory=build main.tex
          xelatex -output-directory=build main.tex  # second pass for TOC/refs

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: build/main.pdf
