name: Build and Commit PDF

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/texlive/texlive:latest-full

    steps:
      - uses: actions/checkout@v4

      - name: Build PDF
        run: latexmk -xelatex -interaction=nonstopmode -file-line-error -outdir=build main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: main-pdf
          path: build/main.pdf

  commit:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: main-pdf
          path: .

      - name: Commit PDF
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add main.pdf
          git commit --allow-empty -m "Update main.pdf [skip ci]"
          git push
