name: Build LaTeX PDF

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install TeX Live and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-xetex \
            texlive-fonts-recommended \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-science \
            texlive-pictures \
            texlive-bibtex-extra \
            latexmk \
            fonts-freefont-ttf \
            lmodern \
            curl \
            file

      - name: Build PDF with xelatex
        run: |
          mkdir -p build
          latexmk -xelatex -output-directory=build main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: build/main.pdf

