name: Build and Commit PDF to Root

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: ghcr.io/xu-cheng/latex:latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build PDF with XeLaTeX
        run: latexmk -xelatex -interaction=nonstopmode -file-line-error -outdir=build main.tex

      - name: Copy PDF to repo root
        run: |
          cp build/main.pdf main.pdf
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add main.pdf
          git commit -m "Update main.pdf [skip ci]" || true
          git push