name: Build and Commit PDF to Root

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: docker.io/texlive/texlive:latest-full

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build PDF with XeLaTeX
        run: latexmk -xelatex -interaction=nonstopmode -file-line-error -outdir=build main.tex

      - name: Copy PDF to repo root
        run: |
          git add main.pdf
          git commit -m "Update main.pdf [skip ci]" || true
          git push